### ISSUE TITLE
Location of defstruct in Module

### ISSUE THREAD

**Issue by wfgilman** [levionessa/elixir_style_guide#106]
In the Modules section, it would be nice to have some guidance on where defstruct should go in relation to @behaviour, use, import, etc.

**Comment by christopheradams** [comment]
In many cases where there's a `@type t` associated with the module that specifies the struct, the `defstruct` either goes right before or right after the `@type` section.

Here are two examples that both look right to me, with `defstruct` [before](https://github.com/elixir-lang/plug/blob/2df667389dbaebb0e2102343c8d7a6ed4de6e280/lib/plug/upload.ex#L26) and [after](https://github.com/elixir-lang/plug/blob/6be2a09f3b86cddb3ab8381aacac4bc475f7f536/lib/plug/conn.ex#L193) the typespecs.

**Comment by christopheradams** [comment]
Just realized this is a duplicate of #95

**Comment by wfgilman** [comment]
My bad. I guess my search wasn't thorough enough.

**Comment by christopheradams** [comment]
Don't worry about it. I overlooked the previous issue too. Does #110 resolve this issue for you?

**Comment by wfgilman** [comment]
Yup that works!

On Tue, Nov 8, 2016 at 12:16 AM, Christopher Adams <notifications@github.com
