### ISSUE TITLE
remove use of PascalCase

### ISSUE THREAD

**Issue by eksperimental** [levionessa/elixir_style_guide#92]
https://github.com/niftyn8/elixir_style_guide/pull/81 has introduced the PascalCase terminology replacing CamelCase as we know it in Elixir.

Please read the [discussion there](https://github.com/niftyn8/elixir_style_guide/pull/81).
I think the PascalCase definition is vague, and the only strong definition of it is adopted mostly by Microsoft, and more over, use of CamelCase terminology in Elixir language is clear, and PascalCase is non existent.
And including it in the style-code is a source of confusion.
IMO 6cbee59f754bb05438b86715f60636c998d42dcf should be reverted until Elixir language itself adopts such terminology --if that ever happens--

**Comment by Qqwy** [comment]
I agree. I don't feel like `PascalCase` is a proper canonical name, and this is actually the first time I heard about it. I don't feel that the Wikipedia is a proper source of truth here, since it does not cite anything outside of Microsoft's website.


Instad, we might want to clarify "upper CamelCase", and we might also call the lower-CamelCase by the name "dromedarisCase", which I think most people will be able to understand.

**Comment by paulfioravanti** [comment]
Under the [Modules section](https://github.com/levionessa/elixir_style_guide#modules) is the statement "Use underscored file names for `CamelCase` module names.", which #81 missed, leading to the inconsistency of module naming being referred to as both `PascalCase` _and_ `CamelCase`.  One should be chosen, and I vote for `CamelCase` over `PascalCase` as well.

**Comment by eksperimental** [comment]
It's been three months, and I just wanted to know if there is anybody who particularly opposes to this change.

Is there anybody against this proposal?
/cc @foresttoney @levionessa

**Comment by christopheradams** [comment]
We should change this. The official docs do not mention`PascalCase`. They do say:

> module names... must be capitalized and written in CamelCase

**Comment by christopheradams** [comment]
Fixed in 1ba79c6

**Comment by eksperimental** [comment]
cool.
thanks @christopheradams
