### ISSUE TITLE
Where does defstruct go in the list?

### ISSUE THREAD

**Issue by dotdotdotpaul** [levionessa/elixir_style_guide#95]
There's a nice list now to show the preferred ordering of things:

```
defmodule MyModule do
  @moduledoc """
  An example module
  """

  use GenServer
  import Something
  import SomethingElse
  alias My.Long.Module.Name
  alias My.Other.Module.Name
  require Integer

  @type params :: [{binary, binary}]

  @module_attribute :foo
  @other_attribute 100

  ...
end
```

But where does defstruct go in this list?  Since it's pretty tightly bound with the module, I figure it should go somewhere near the top, but I could see the defaults needing/wanting to use aliases, or perhaps the module attributes...  I hesitate to put it too far "down" the list because then it may not be so obvious that the module is actually a struct...  Suggestions?

**Comment by Qqwy** [comment]
I would suggest putting `defstruct` after the alias/require lines, and at about the same height as types and module attributes. (In front of it, unless you want to use them inside the struct definition, which might be the case)
